Description: Plantilla para crear instancias Server y Cliente con Security Group

Parameters:
  KeyName:
    Description: Nombre de la key pair
    Type: String
    Default: vockey

  VpcId:
    Description: VPC donde se creara el Security Group
    Type: AWS::EC2::VPC::Id

Resources:

  ############################################################
  # SECURITY GROUP
  ############################################################
  OpenLDAPAMSASG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Ref VpcId
      GroupDescription: Security group para OpenLDAP AMSA Server y Client
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 389
          ToPort: 389
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 636
          ToPort: 636
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: OpenLDAP-AMSA-SG-AutoCreated


  ############################################################
  # INSTANCIA SERVER
  ############################################################
  OpenLDAPAMSAServer:
    Type: AWS::EC2::Instance
    DependsOn: OpenLDAPAMSASG
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M      # Tiempo para que termine el bash
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref OpenLDAPAMSASG
      KeyName: !Ref KeyName
      ImageId: ami-0fa3fe0fa7920f68e
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /home/ec2-user/ServerInstall.log 2>&1
          set -xe

          sudo yum update -y
          sudo yum install -y git aws-cfn-bootstrap

          sudo git clone https://github.com/IvanGilC/amsa2.git /opt/amsa

          cd /opt/amsa
          sudo bash amsa_p3_server.sh
          sudo bash amsa_p3_lam.sh

          # Python HTTP Server para pasar el certificado al cliente
          cd /etc/pki/tls
          nohup python3 -m http.server 8080 &

          # Señalar a CloudFormation que el servidor esta listo
          /opt/aws/bin/cfn-signal --success true --stack ${AWS::StackName} --resource OpenLDAPAMSAServer --region ${AWS::Region}

      Tags:
        - Key: Name
          Value: OpenLDAP-AMSA-Server-AutoCreated


  ############################################################
  # INSTANCIA CLIENTE
  ############################################################
  OpenLDAPAMSAClient:
    Type: AWS::EC2::Instance
    DependsOn: OpenLDAPAMSAServer    # Espera a que termine el server
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref OpenLDAPAMSASG
      KeyName: !Ref KeyName
      ImageId: ami-0fa3fe0fa7920f68e
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > /home/ec2-user/ClientInstall.log 2>&1
          set -xe
          sudo yum update -y
          sudo yum install git -y

          sudo git clone https://github.com/IvanGilC/amsa2.git /opt/amsa
          
          cd /opt/amsa
          export LDAP_SERVER=${OpenLDAPAMSAServer.PublicDnsName}
          sudo bash amsa_p3_client.sh $LDAP_SERVER

      Tags:
        - Key: Name
          Value: OpenLDAP-AMSA-Client-AutoCreated